hack to appease docker builds

diff --git a/etc/debian/postinst b/etc/debian/postinst
--- a/etc/debian/postinst
+++ b/etc/debian/postinst
@@ -23,7 +23,7 @@ case "$1" in
 
 	if [ -x /bin/systemctl ]; then
 		install -m644 /usr/share/doc/ot-recorder/ot-recorder.service /etc/systemd/system/ot-recorder.service
-		systemctl --system daemon-reload
+		systemctl --system daemon-reload || exit 0 # catch failure in docker setup
 	fi
     ;;
 
